#Please do not change the config version it could break the plugin.
config-version: 3

tps-check-interval-ticks: 200
tps-threshold: 18.0
clear-types:
    - DROPPED_ITEM
    - EXPERIENCE_ORB
    - FIREWORK
    - AREA_EFFECT_CLOUD
    - FALLING_BLOCK

skip:
  named: true
  tamed: true
  villagers: true
  armor-stands: true
  item-frames: true
  paintings: true
  vehicles: true
  citizens-npc: true
region-safe: true
towny-safe: true
